/* --- AUTOGENERATED --- */

export const RouteServices = Object.freeze( /** @type {const} */ (/* RouteServices */))

export const RouteService = Object.freeze(/** @type {const} */ (/* RouteService */))

export const ServiceRoutes = Object.freeze(/** @type {const} */ (/* ServiceRoutes */))
