export const Key = /** @type {const} */ ({
  'checkin': 'checkin',
  'user': 'user',
  'users': 'users',
  'role': 'role',
  'roles': 'roles',
  'country': 'country',
  'countries': 'countries',
  'currency': 'currency',
  'currencies': 'currencies',
  'timezone': 'timezone',
  'timezones': 'timezones',
  'city': 'city',
  'cities': 'cities',
  'venue': 'venue',
  'venues': 'venues',
  'theme': 'theme',
  'themes': 'themes',
  'cover': 'cover',
  'game': 'game',
  'games': 'games',
  'registration': 'registration',
  'registrations': 'registrations',
  'export': 'export',
  'password': 'password',
  'vk_group_token': 'vk_group_token',
  'summary': 'summary',
  'mailing': 'mailing',
  'channel': 'channel',
  'status': 'status',
  'statuses': 'statuses',
  'creation': 'creation',
  'confirmation': 'confirmation',
  'cancellation': 'cancellation',
  'lineup': 'lineup',
  'lineups': 'lineups',
  'telegram': 'telegram',
  'chatapp': 'chatapp',
  'bitrix': 'bitrix',
  'webhook': 'webhook',
  'source': 'source',
  'search': 'search',
})

export const Keys = Object.values(Key)
