import { Pattern } from './pattern.js'
import { Service } from './services.js'

export const Segments = Object.freeze(
  /** @type {const} */ ([
    Object.freeze(
      /** @type {const} */ ({
        key: '',
        cardinality: '1',
        singular: '',
        plural: '',
        service: null,
        pattern: null,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'checkin',
        cardinality: '1',
        singular: 'checkin',
        plural: 'checkins',
        service: Service.Checkin,
        pattern: null,
        kind: 'Operation',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'user',
        cardinality: '1',
        singular: 'user',
        plural: 'users',
        service: Service.Users,
        pattern: Pattern.UUID.source,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'users',
        cardinality: 'n',
        singular: 'user',
        plural: 'users',
        service: Service.Users,
        pattern: null,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'role',
        cardinality: '1',
        singular: 'role',
        plural: 'roles',
        service: Service.Roles,
        pattern: Pattern.UUID.source,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'roles',
        cardinality: 'n',
        singular: 'role',
        plural: 'roles',
        service: Service.Roles,
        pattern: null,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'country',
        cardinality: '1',
        singular: 'country',
        plural: 'countries',
        service: Service.Locations,
        pattern: Pattern.COUNTRY_CODE.source,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'countries',
        cardinality: 'n',
        singular: 'country',
        plural: 'countries',
        service: Service.Locations,
        pattern: null,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'currency',
        cardinality: '1',
        singular: 'currency',
        plural: 'currencies',
        service: Service.Locations,
        pattern: Pattern.CURRENCY_CODE.source,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'currencies',
        cardinality: 'n',
        singular: 'currency',
        plural: 'currencies',
        service: Service.Locations,
        pattern: null,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'timezone',
        cardinality: '1',
        singular: 'timezone',
        plural: 'timezones',
        service: Service.Locations,
        pattern: Pattern.TIMEZONE_NAME.source,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'timezones',
        cardinality: 'n',
        singular: 'timezone',
        plural: 'timezones',
        service: Service.Locations,
        pattern: null,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'city',
        cardinality: '1',
        singular: 'city',
        plural: 'cities',
        service: Service.Cities,
        pattern: Pattern.UUID.source,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'cities',
        cardinality: 'n',
        singular: 'city',
        plural: 'cities',
        service: Service.Cities,
        pattern: null,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'venue',
        cardinality: '1',
        singular: 'venue',
        plural: 'venues',
        service: Service.Venues,
        pattern: Pattern.UUID.source,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'venues',
        cardinality: 'n',
        singular: 'venue',
        plural: 'venues',
        service: Service.Venues,
        pattern: null,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'theme',
        cardinality: '1',
        singular: 'theme',
        plural: 'themes',
        service: Service.Themes,
        pattern: Pattern.UUID.source,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'themes',
        cardinality: 'n',
        singular: 'theme',
        plural: 'themes',
        service: Service.Themes,
        pattern: null,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'cover',
        cardinality: '1',
        singular: 'cover',
        plural: 'covers',
        service: Service.Minio,
        pattern: Pattern.UUID.source,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'covers',
        cardinality: 'n',
        singular: 'cover',
        plural: 'covers',
        service: Service.Minio,
        pattern: null,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'game',
        cardinality: '1',
        singular: 'game',
        plural: 'games',
        service: Service.Games,
        pattern: Pattern.UUID.source,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'games',
        cardinality: 'n',
        singular: 'game',
        plural: 'games',
        service: Service.Games,
        pattern: null,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'registration',
        cardinality: '1',
        singular: 'registration',
        plural: 'registrations',
        service: Service.Registrations,
        pattern: Pattern.UUID.source,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'registrations',
        cardinality: 'n',
        singular: 'registration',
        plural: 'registrations',
        service: Service.Registrations,
        pattern: null,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'status',
        cardinality: '1',
        singular: 'status',
        plural: 'statuses',
        service: null,
        pattern: null,
        kind: 'Property',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'statuses',
        cardinality: 'n',
        singular: 'status',
        plural: 'statuses',
        service: null,
        pattern: null,
        kind: 'Property',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'creation',
        cardinality: '1',
        singular: 'creation',
        plural: 'creations',
        service: null,
        pattern: null,
        kind: 'Operation',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'verification',
        cardinality: '1',
        singular: 'verification',
        plural: 'verifications',
        service: null,
        pattern: null,
        kind: 'Operation',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'landing',
        cardinality: '1',
        singular: 'landing',
        plural: 'landings',
        service: null,
        pattern: null,
        kind: 'Integration',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'vkma',
        cardinality: '1',
        singular: 'vkma',
        plural: 'vkmas',
        service: null,
        pattern: null,
        kind: 'Integration',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'hub',
        cardinality: '1',
        singular: 'hub',
        plural: 'hubs',
        service: null,
        pattern: null,
        kind: 'Integration',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'team',
        cardinality: '1',
        singular: 'team',
        plural: 'teams',
        service: null,
        pattern: null,
        kind: 'Integration',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'group',
        cardinality: '1',
        singular: 'group',
        plural: 'groups',
        service: null,
        pattern: null,
        kind: 'Integration',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'confirmation',
        cardinality: '1',
        singular: 'confirmation',
        plural: 'confirmations',
        service: null,
        pattern: null,
        kind: 'Operation',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'cancellation',
        cardinality: '1',
        singular: 'cancellation',
        plural: 'cancellations',
        service: null,
        pattern: null,
        kind: 'Operation',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'reinstatement',
        cardinality: '1',
        singular: 'reinstatement',
        plural: 'reinstatements',
        service: null,
        pattern: null,
        kind: 'Operation',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'restoration',
        cardinality: '1',
        singular: 'restoration',
        plural: 'restorations',
        service: null,
        pattern: null,
        kind: 'Operation',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'lineup',
        cardinality: '1',
        singular: 'lineup',
        plural: 'lineups',
        service: null,
        pattern: null,
        kind: 'Property',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'lineups',
        cardinality: 'n',
        singular: 'lineup',
        plural: 'lineups',
        service: null,
        pattern: null,
        kind: 'Property',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'promotion',
        cardinality: '1',
        singular: 'promotion',
        plural: 'promotions',
        service: null,
        pattern: null,
        kind: 'Operation',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'reservation',
        cardinality: '1',
        singular: 'reservation',
        plural: 'reservations',
        service: null,
        pattern: null,
        kind: 'Operation',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'telegram',
        cardinality: '1',
        singular: 'telegram',
        plural: 'telegrams',
        service: Service.Telegram,
        pattern: null,
        kind: 'Integration',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'chatapp',
        cardinality: '1',
        singular: 'chatapp',
        plural: 'chatapps',
        service: Service.Chatapp,
        pattern: null,
        kind: 'Integration',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'bitrix',
        cardinality: '1',
        singular: 'bitrix',
        plural: 'bitrixes',
        service: Service.Bitrix,
        pattern: null,
        kind: 'Integration',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'vk',
        cardinality: '1',
        singular: 'vk',
        plural: 'vks',
        service: Service.Vk,
        pattern: null,
        kind: 'Integration',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'max',
        cardinality: '1',
        singular: 'max',
        plural: 'maxes',
        service: Service.Max,
        pattern: null,
        kind: 'Integration',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'vk-organizer',
        cardinality: '1',
        singular: 'vk-organizer',
        plural: 'vk-organizers',
        service: Service.VkOrganizer,
        pattern: null,
        kind: 'Integration',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'webhook',
        cardinality: '1',
        singular: 'webhook',
        plural: 'webhooks',
        service: null,
        pattern: null,
        kind: 'Integration',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'source',
        cardinality: '1',
        singular: 'source',
        plural: 'sources',
        service: Service.Updates,
        pattern: null,
        kind: 'Integration',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'search',
        cardinality: '1',
        singular: 'search',
        plural: 'searches',
        service: null,
        pattern: null,
        kind: 'Integration',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'export',
        cardinality: '1',
        singular: 'export',
        plural: 'exports',
        service: null,
        pattern: null,
        kind: 'Operation',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'password',
        cardinality: '1',
        singular: 'password',
        plural: 'passwords',
        service: null,
        pattern: null,
        kind: 'Property',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'vk_group_token',
        cardinality: '1',
        singular: 'vk_group_token',
        plural: 'vk_group_tokens',
        service: null,
        pattern: null,
        kind: 'Property',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'summary',
        cardinality: '1',
        singular: 'summary',
        plural: 'summaries',
        service: null,
        pattern: null,
        kind: 'Aggregation',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'mailing',
        cardinality: '1',
        singular: 'mailing',
        plural: 'mailings',
        service: null,
        pattern: null,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'message',
        cardinality: '1',
        singular: 'message',
        plural: 'messages',
        service: null,
        pattern: null,
        kind: 'Entity',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'channel',
        cardinality: '1',
        singular: 'channel',
        plural: 'channels',
        service: null,
        pattern: null,
        kind: 'Property',
      }),
    ),
    Object.freeze(
      /** @type {const} */ ({
        key: 'dialog',
        cardinality: '1',
        singular: 'dialog',
        plural: 'dialogs',
        service: null,
        pattern: null,
        kind: 'Property',
      }),
    ),
  ]),
)

export const Segment = Object.freeze(
  /** @type {{ [x in typeof Segments[number]['key']]: Extract<typeof Segments[number], { key: x }> }} */ (
    Segments.reduce(
      (o, x) => (o[x.key] = x, o),
      {},
    )
  ),
)
