export const Service = Object.freeze({
  'Users': 'Users',
  'Roles': 'Roles',
  'Checkin': 'Checkin',
  'Locations': 'Locations',
  'Cities': 'Cities',
  'Venues': 'Venues',
  'Themes': 'Themes',
  'Games': 'Games',
  'Registrations': 'Registrations',
  'Files': 'Files',
  'Procedures': 'Procedures',
  'Integrations': 'Integrations',
  'Updates': 'Updates',
  'Hub': 'Hub',
  'Landing': 'Landing',
  'Vkma': 'Vkma',
  'Minio': 'Minio',
})

export const Services = Object.freeze([
  'Users',
  'Roles',
  'Checkin',
  'Locations',
  'Cities',
  'Venues',
  'Themes',
  'Games',
  'Registrations',
  'Files',
  'Procedures',
  'Integrations',
  'Updates',
  'Hub',
  'Landing',
  'Vkma',
  'Minio',
])
