export let Service = /** @type {const} */ ({
  Users: 'Users',
  Roles: 'Roles',
  Checkin: 'Checkin',
  Locations: 'Locations',
  Cities: 'Cities',
  Venues: 'Venues',
  Themes: 'Themes',
  Games: 'Games',
  Registrations: 'Registrations',
  Procedures: 'Procedures',
  Updates: 'Updates',
  Hub: 'Hub',
  Landing: 'Landing',
  Vkma: 'Vkma',
  Telegram: 'Telegram',
  Chatapp: 'Chatapp',
  Bitrix: 'Bitrix',
  Vk: 'Vk',
  Max: 'Max',
  VkOrganizer: 'VkOrganizer',
  Reposter: 'Reposter',
  Raffle: 'Raffle',
  Minio: 'Minio',
})

export let Services = Object.values(Service)
