export var GameColumns = /** @type {const} */ ({
  alias: 'alias',
  city_id: 'city_id',
  created_by_id: 'created_by_id',
  currency: 'currency',
  description: 'description',
  event_time: 'event_time',
  game_pack_id: 'game_pack_id',
  id: 'id',
  image_id: 'image_id',
  location_id: 'location_id',
  max_members_count: 'max_members_count',
  min_members_count: 'min_members_count',
  name: 'name',
  number: 'number',
  owner_id: 'owner_id',
  personal_comment: 'personal_comment',
  price: 'price',
  short_description: 'short_description',
  status: 'status',
  theme_id: 'theme_id',
  time_created: 'time_created',
  time_updated: 'time_updated',
  timezone: 'timezone',
  weekday: 'weekday',
})
