export var UserColumns = /** @type {const} */ ({
  email: 'email',
  first_name: 'first_name',
  gmail_link: 'gmail_link',
  hashed_password: 'hashed_password',
  id: 'id',
  image_id: 'image_id',
  is_active: 'is_active',
  is_superuser: 'is_superuser',
  is_verified: 'is_verified',
  last_name: 'last_name',
  mailru_link: 'mailru_link',
  phone: 'phone',
  role_id: 'role_id',
  telegram_data: 'telegram_data',
  telegram_id: 'telegram_id',
  third_name: 'third_name',
  time_created: 'time_created',
  time_updated: 'time_updated',
})
