export var VenueColumns = /** @type {const} */ ({
  city_id: 'city_id',
  comment: 'comment',
  comment_equipment: 'comment_equipment',
  comment_responsible: 'comment_responsible',
  floor: 'floor',
  game_time: 'game_time',
  house_number: 'house_number',
  id: 'id',
  is_adult: 'is_adult',
  latitude: 'latitude',
  location_info: 'location_info',
  longitude: 'longitude',
  metro: 'metro',
  name: 'name',
  people_capacity: 'people_capacity',
  street: 'street',
  team_capacity: 'team_capacity',
  time_created: 'time_created',
  time_updated: 'time_updated',
})
