import { RouteParameters } from '../codegen/autogenerated.js'

/**
 * @param {keyof typeof import('@shakerquiz/utilities').Route} route
 */
export const props = route =>
  RouteParameters[route]
    .map(param => param.replace(':', '') + '_id')

/**
 * @param {keyof typeof import('@shakerquiz/utilities').Route} route
 * @param {object} value
 */
export const params = (route, value) =>
  props(route)
    .map(prop => value[prop])
    .filter(Boolean)
