export var Feature = /** @type {const} */ ({
  'Users': 'Users',
  'User': 'User',
  'Roles': 'Roles',
  'Role': 'Role',
  'Checkins': 'Checkins',
  'Checkin': 'Checkin',
  'Countries': 'Countries',
  'Country': 'Country',
  'Currencies': 'Currencies',
  'Currency': 'Currency',
  'Cities': 'Cities',
  'City': 'City',
  'Venues': 'Venues',
  'Venue': 'Venue',
  'Games': 'Games',
  'Game': 'Game',
  'Themes': 'Themes',
  'Theme': 'Theme',
  'Registrations': 'Registrations',
  'Registration': 'Registration',
  'Mailings': 'Mailings',
  'Mailing': 'Mailing',
})

/** @type {Record<Feature, Icon>} */
export var FeatureIcon = {
  [Feature.Users]: 'hero/solid/users',
  [Feature.User]: 'hero/solid/users',
  [Feature.Roles]: 'hero/solid/identification',
  [Feature.Role]: 'hero/solid/identification',
  [Feature.Checkins]: 'arrow-right-end-on-rectangle',
  [Feature.Checkin]: 'arrow-right-end-on-rectangle',
  [Feature.Countries]: 'hero/outline/no-symbol',
  [Feature.Country]: 'hero/outline/no-symbol',
  [Feature.Currencies]: 'hero/outline/banknotes',
  [Feature.Currency]: 'hero/outline/banknotes',
  [Feature.Cities]: 'hero/outline/building-office',
  [Feature.City]: 'hero/outline/building-office',
  [Feature.Venues]: 'hero/outline/map-pin',
  [Feature.Venue]: 'hero/outline/map-pin',
  [Feature.Games]: 'hero/outline/newspaper',
  [Feature.Game]: 'hero/outline/newspaper',
  [Feature.Themes]: 'hero/outline/document-text',
  [Feature.Theme]: 'hero/outline/document-text',
  [Feature.Registrations]: 'hero/outline/user-group',
  [Feature.Registration]: 'hero/outline/user-group',
  [Feature.Mailings]: 'hero/outline/envelope',
  [Feature.Mailing]: 'hero/outline/envelope',
}
