export var Feature = /** @type {const} */ ({
  'users': 'users',
  'user': 'user',
  'roles': 'roles',
  'role': 'role',
  'checkins': 'checkins',
  'checkin': 'checkin',
  'countries': 'countries',
  'country': 'country',
  'currencies': 'currencies',
  'currency': 'currency',
  'cities': 'cities',
  'city': 'city',
  'venues': 'venues',
  'venue': 'venue',
  'games': 'games',
  'game': 'game',
  'themes': 'themes',
  'theme': 'theme',
  'registrations': 'registrations',
  'registration': 'registration',
  'mailings': 'mailings',
  'mailing': 'mailing',
})

export var Features = Object.values(Feature)

/** @type {Record<Feature, Icon>} */
export var FeatureIcon = {
  [Feature.users]: 'hero/solid/users',
  [Feature.user]: 'hero/solid/users',
  [Feature.roles]: 'hero/solid/identification',
  [Feature.role]: 'hero/solid/identification',
  [Feature.checkins]: 'arrow-right-end-on-rectangle',
  [Feature.checkin]: 'arrow-right-end-on-rectangle',
  [Feature.countries]: 'hero/outline/no-symbol',
  [Feature.country]: 'hero/outline/no-symbol',
  [Feature.currencies]: 'hero/outline/banknotes',
  [Feature.currency]: 'hero/outline/banknotes',
  [Feature.cities]: 'hero/outline/building-office',
  [Feature.city]: 'hero/outline/building-office',
  [Feature.venues]: 'hero/outline/map-pin',
  [Feature.venue]: 'hero/outline/map-pin',
  [Feature.games]: 'hero/outline/newspaper',
  [Feature.game]: 'hero/outline/newspaper',
  [Feature.themes]: 'hero/outline/document-text',
  [Feature.theme]: 'hero/outline/document-text',
  [Feature.registrations]: 'hero/outline/user-group',
  [Feature.registration]: 'hero/outline/user-group',
  [Feature.mailings]: 'hero/outline/envelope',
  [Feature.mailing]: 'hero/outline/envelope',
}
