export var Route = /** @type {const} */ ({
  'role': 'role',
  'roles': 'roles',
  'user': 'user',
  'users': 'users',
  'checkin': 'checkin',
  'user/password': 'user/password',
  'user/role': 'user/role',
  'user/cities': 'user/cities',
  'users/role': 'users/role',
  'users/cities': 'users/cities',
  'countries': 'countries',
  'currencies': 'currencies',
  'city': 'city',
  'cities': 'cities',
  'city/venues': 'city/venues',
  'venue': 'venue',
  'venues': 'venues',
  'venues/city': 'venues/city',
  'theme': 'theme',
  'themes': 'themes',
  'theme/cover': 'theme/cover',
  'themes/covers': 'themes/covers',
  'game': 'game',
  'game/registrations': 'game/registrations',
  'games': 'games',
  'registration': 'registration',
  'registration/mailing': 'registration/mailing',
  'registrations': 'registrations',
  'mailing': 'mailing',
})

export var Routes = Object.values(Route)

export var RoutePathname = /** @type {const} */ ({
  [Route['role']]: 'role/:role',
  [Route['roles']]: 'roles',
  [Route['user']]: 'user/:user',
  [Route['users']]: 'users',
  [Route['checkin']]: 'checkin',
  [Route['user/password']]: 'user/:user/password',
  [Route['user/role']]: 'user/:user/role',
  [Route['user/cities']]: 'user/:user/cities',
  [Route['users/role']]: 'users/role',
  [Route['users/cities']]: 'users/cities',
  [Route['countries']]: 'countries',
  [Route['currencies']]: 'currencies',
  [Route['city']]: 'city/:city',
  [Route['cities']]: 'cities',
  [Route['city/venues']]: 'city/:city/venues',
  [Route['venue']]: 'venue/:venue',
  [Route['venues']]: 'venues',
  [Route['venues/city']]: 'venues/city',
  [Route['theme']]: 'theme/:theme',
  [Route['themes']]: 'themes',
  [Route['theme/cover']]: 'theme/:theme/cover',
  [Route['themes/covers']]: 'themes/covers',
  [Route['game']]: 'game/:game',
  [Route['game/registrations']]: 'game/:game/registrations',
  [Route['games']]: 'games',
  [Route['registration']]: 'registration/:registration',
  [Route['registration/mailing']]: 'registration/:registration/mailing',
  [Route['registrations']]: 'registrations',
  [Route['mailing']]: 'mailing/:mailing',
})

export var RoutePathnames = Object.values(RoutePathname)

export var RouteParams = /** @type {const} */ ({
  [Route['role']]: [':role'],
  [Route['roles']]: [],
  [Route['user']]: [':user'],
  [Route['user/password']]: [':user'],
  [Route['user/role']]: [':user'],
  [Route['user/cities']]: [':user'],
  [Route['users']]: [],
  [Route['users/role']]: [],
  [Route['users/cities']]: [],
  [Route['checkin']]: [],
  [Route['countries']]: [],
  [Route['currencies']]: [],
  [Route['city']]: [':city'],
  [Route['city/venues']]: [':city'],
  [Route['cities']]: [],
  [Route['venue']]: [':venue'],
  [Route['venues']]: [],
  [Route['venues/city']]: [],
  [Route['theme']]: [':theme'],
  [Route['theme/cover']]: [':theme'],
  [Route['themes']]: [],
  [Route['themes/covers']]: [],
  [Route['game']]: [':game'],
  [Route['game/registrations']]: [':game'],
  [Route['games']]: [],
  [Route['registration']]: [':registration'],
  [Route['registration/mailing']]: [':registration'],
  [Route['registrations']]: [],
  [Route['mailing']]: [':mailing'],
})

export var RouteService = {
  [Route['role']]: 'Roles',
  [Route['roles']]: 'Roles',
  [Route['user']]: 'Users',
  [Route['user/password']]: 'Users',
  [Route['user/role']]: 'Users',
  [Route['user/cities']]: 'Users',
  [Route['users']]: 'Users',
  [Route['users/role']]: 'Users',
  [Route['users/cities']]: 'Users',
  [Route['checkin']]: 'Checkin',
  [Route['countries']]: 'Locations',
  [Route['currencies']]: 'Locations',
  [Route['city']]: 'Cities',
  [Route['city/venues']]: 'Cities',
  [Route['cities']]: 'Cities',
  [Route['venue']]: 'Venues',
  [Route['venues']]: 'Venues',
  [Route['venues/city']]: 'Venues',
  [Route['theme']]: 'Themes',
  [Route['theme/cover']]: 'Themes',
  [Route['themes']]: 'Themes',
  [Route['themes/covers']]: 'Themes',
  [Route['game']]: 'Games',
  [Route['game/registrations']]: 'Games',
  [Route['games']]: 'Games',
  [Route['registration']]: 'Registrations',
  [Route['registration/mailing']]: 'Registrations',
  [Route['registrations']]: 'Registrations',
  [Route['mailing']]: 'Games',
}

/**
 * @template {Route} R
 * @template {typeof RouteParams[R]} P
 *
 * @param {R} route
 * @param {Record<P[number] extends `:${infer Name}` ? Name : P[number], string>} params
 */
export var hydrateRoutePathname = (route, params) =>
  RouteParams[route].reduce(
    (pathname, param) => pathname.replace(param, params[param.replace(':', '')]),
    RoutePathname[route],
  )
