import template from './template.js' with { type: 'text' }

import { Routes } from '../source/entities/routes.js'
import { Segment, Segments } from '../source/entities/segment.js'

let pathname = route =>
  route
    .split('/')
    .map(x => {
      if (!Segment[x].pattern)
        return x
      else if (Segment[x].cardinality === '1')
        return `${x}/:${x}`
      else
        return x
    })
    .join('/')

let parameters = pathname =>
  pathname
    .split('/')
    .filter(x => x.includes(':'))

let breakdown = route =>
  route
    .split('/')
    .map((x, i) => {
      if (i > 0)
        return x
      else if (Segment[x].cardinality === '1')
        return x
      else
        return Segment[x].relation
    })
    .join('/')

let service = route =>
  route
    .split('/')
    .slice(0, 1)
    .map(x => Segment[x].service)
    .at(0)

let Route = Routes
  .map(x => `'${x}': '${x}'`)
  .join(',\n    ')

let RouteCardinality = Routes
  .map(route => [
    route,
    route.split('/').map(a => Segment[a].cardinality),
  ])
  .map(([route, cardinalities]) => [
    route,
    cardinalities.length > 1
      ? cardinalities.at(0) + '/' + cardinalities.at(-1)
      : cardinalities.at(0),
  ])
  .map(([route, cardinality]) => `'${route}': '${cardinality}'`)
  .join(',\n    ')

let RoutePathname = Routes
  .map(x => `'${x}': '${pathname(x)}'`)
  .join(',\n    ')

let PathnameRoute = Routes
  .map(x => `'${pathname(x)}': '${x}'`)
  .join(',\n    ')

let PathnameParameters = Routes
  .map(x => `'${pathname(x)}': ${JSON.stringify(parameters(pathname(x)), null, 2)}`)
  .join(',\n    ')

let ParameterPattern = Segments
  .filter(x => x.pattern)
  .map(x => `':${x.key}': '${x.pattern}'`)
  .join(',\n    ')

let RouteBreakdown = Routes
  .map(x => `'${x}': '${breakdown(x)}'`)
  .join(',\n    ')

let RouteService = Routes
  .map(x => `'${x}': '${service(x)}'`)
  .join(',\n    ')

let ServiceRoutes = Object
  .entries(Object.groupBy(Routes, service))
  .map(([service, routes]) => `'${service}': ${JSON.stringify(routes, null, 2)}`)
  .join(',\n    ')

Bun.write(
  './source/codegen/autogenerated.js',
  template
    .replace('/* route */', Route)
    .replace('/* route -> cardinality */', RouteCardinality)
    .replace('/* route -> pathname */', RoutePathname)
    .replace('/* pathname -> route */', PathnameRoute)
    .replace('/* pathname -> parameters */', PathnameParameters)
    .replace('/* parameter -> pattern */', ParameterPattern)
    .replace('/* route -> breakdown */', RouteBreakdown)
    .replace('/* route -> service */', RouteService)
    .replace('/* service -> routes */', ServiceRoutes),
)
