/* --- Autogenerated --- */

export const RouteCardinality = Object.freeze(
  /** @type {const} */ ({
    /* route -> cardinality */
  }),
)

export const RoutePathname = Object.freeze(
  /** @type {const} */ ({
    /* route -> pathname */
  }),
)

export const PathnameRoute = Object.freeze(
  /** @type {const} */ ({
    /* pathname -> route */
  }),
)

export const PathnameParameters = Object.freeze(
  /** @type {const} */ ({
    /* pathname -> parameters */
  }),
)

export const ParameterPattern = Object.freeze(
  /** @type {const} */ ({
    /* parameter -> pattern */
  }),
)

export const RouteBreakdown = Object.freeze(
  /** @type {const} */ ({
    /* route -> breakdown */
  }),
)

export const RouteService = Object.freeze(
  /** @type {const} */ ({
    /* route -> service */
  }),
)

export const ServiceRoutes = Object.freeze(
  /** @type {const} */ ({
    /* service -> routes */
  }),
)
