import { Cardinality } from './cardinality.js'
import { Service } from './service.js'

export const Route = Object.freeze({
  'checkin': 'checkin',
  'cities': 'cities',
  'cities/country': 'cities/country',
  'cities/currency': 'cities/currency',
  'cities/timezone': 'cities/timezone',
  'cities/venues': 'cities/venues',
  'city': 'city',
  'city/country': 'city/country',
  'city/currency': 'city/currency',
  'city/timezone': 'city/timezone',
  'city/venue': 'city/venue',
  'city/venues': 'city/venues',
  'countries': 'countries',
  'country': 'country',
  'currencies': 'currencies',
  'currency': 'currency',
  'game': 'game',
  'game/city': 'game/city',
  'game/registration': 'game/registration',
  'game/registrations': 'game/registrations',
  'game/registrations/export': 'game/registrations/export',
  'game/summary': 'game/summary',
  'game/theme': 'game/theme',
  'game/venue': 'game/venue',
  'games': 'games',
  'games/city': 'games/city',
  'games/registrations': 'games/registrations',
  'games/registrations/export': 'games/registrations/export',
  'games/summary': 'games/summary',
  'games/theme': 'games/theme',
  'games/venue': 'games/venue',
  'registration': 'registration',
  'registration/cancellation': 'registration/cancellation',
  'registration/channel': 'registration/channel',
  'registration/confirmation': 'registration/confirmation',
  'registration/export': 'registration/export',
  'registration/game': 'registration/game',
  'registration/game/theme': 'registration/game/theme',
  'registration/mailing': 'registration/mailing',
  'registrations': 'registrations',
  'registrations/city': 'registrations/city',
  'registrations/game': 'registrations/game',
  'registrations/game/theme': 'registrations/game/theme',
  'registrations/export': 'registrations/export',
  'role': 'role',
  'roles': 'roles',
  'theme': 'theme',
  'theme/cover': 'theme/cover',
  'themes': 'themes',
  'themes/cover': 'themes/cover',
  'timezone': 'timezone',
  'timezones': 'timezones',
  'user': 'user',
  'user/cities': 'user/cities',
  'user/city': 'user/city',
  'user/password': 'user/password',
  'user/role': 'user/role',
  'users': 'users',
  'users/cities': 'users/cities',
  'users/password': 'users/password',
  'users/role': 'users/role',
  'venue': 'venue',
  'venue/city': 'venue/city',
  'venues': 'venues',
  'venues/city': 'venues/city',
})

export const Routes = Object.freeze(Object.values(Route))

export const RouteCardinality = Object.freeze({
  [Route['checkin']]: Cardinality['1'],
  [Route['cities']]: Cardinality['N'],
  [Route['cities/country']]: Cardinality['N-1'],
  [Route['cities/currency']]: Cardinality['N-1'],
  [Route['cities/timezone']]: Cardinality['N-1'],
  [Route['cities/venues']]: Cardinality['N-N'],
  [Route['city']]: Cardinality['1'],
  [Route['city/country']]: Cardinality['1-1'],
  [Route['city/currency']]: Cardinality['1-1'],
  [Route['city/timezone']]: Cardinality['1-1'],
  [Route['city/venue']]: Cardinality['1-1'],
  [Route['city/venues']]: Cardinality['1-N'],
  [Route['countries']]: Cardinality['N'],
  [Route['country']]: Cardinality['1'],
  [Route['currencies']]: Cardinality['N'],
  [Route['currency']]: Cardinality['1'],
  [Route['game']]: Cardinality['1'],
  [Route['game/city']]: Cardinality['1-1'],
  [Route['game/registration']]: Cardinality['1-1'],
  [Route['game/registrations']]: Cardinality['1-N'],
  [Route['game/registrations/export']]: Cardinality['1'],
  [Route['game/summary']]: Cardinality['1-1'],
  [Route['game/theme']]: Cardinality['1-1'],
  [Route['game/venue']]: Cardinality['1-1'],
  [Route['games']]: Cardinality['N'],
  [Route['games/city']]: Cardinality['N-1'],
  [Route['games/registrations']]: Cardinality['N-N'],
  [Route['games/registrations/export']]: Cardinality['1'],
  [Route['games/summary']]: Cardinality['N-1'],
  [Route['games/theme']]: Cardinality['N-1'],
  [Route['games/venue']]: Cardinality['N-1'],
  [Route['registration']]: Cardinality['1'],
  [Route['registration/game/theme']]: Cardinality['1-1'],
  [Route['registration/export']]: Cardinality['1'],
  [Route['registrations']]: Cardinality['N'],
  [Route['registrations/city']]: Cardinality['N-1'],
  [Route['registrations/game']]: Cardinality['N-1'],
  [Route['registrations/game/theme']]: Cardinality['N-1'],
  [Route['registrations/export']]: Cardinality['1'],
  [Route['role']]: Cardinality['1'],
  [Route['roles']]: Cardinality['N'],
  [Route['theme']]: Cardinality['1'],
  [Route['theme/cover']]: Cardinality['1-1'],
  [Route['themes']]: Cardinality['N'],
  [Route['themes/cover']]: Cardinality['N-1'],
  [Route['timezone']]: Cardinality['1'],
  [Route['timezones']]: Cardinality['N'],
  [Route['user']]: Cardinality['1'],
  [Route['user/cities']]: Cardinality['1-N'],
  [Route['user/city']]: Cardinality['1-1'],
  [Route['user/password']]: Cardinality['1-1'],
  [Route['user/role']]: Cardinality['1-1'],
  [Route['users']]: Cardinality['N'],
  [Route['users/cities']]: Cardinality['N-N'],
  [Route['users/role']]: Cardinality['N-1'],
  [Route['venue']]: Cardinality['1'],
  [Route['venue/city']]: Cardinality['1-1'],
  [Route['venues']]: Cardinality['N'],
  [Route['venues/city']]: Cardinality['N-1'],
})

export const RouteRelation = Object.freeze({
  [Route['cities']]: Route['city'],
  [Route['cities/country']]: Route['city/country'],
  [Route['cities/currency']]: Route['city/currency'],
  [Route['cities/timezone']]: Route['city/timezone'],
  [Route['cities/venues']]: Route['city/venues'],
  [Route['city/venues']]: Route['city/venues'],
  [Route['countries']]: Route['country'],
  [Route['currencies']]: Route['currency'],
  [Route['game/registrations']]: Route['game/registrations'],
  [Route['games']]: Route['game'],
  [Route['games/city']]: Route['game/city'],
  [Route['games/registrations']]: Route['game/registrations'],
  [Route['games/summary']]: Route['game/summary'],
  [Route['games/theme']]: Route['game/theme'],
  [Route['games/venue']]: Route['game/venue'],
  [Route['registrations']]: Route['registration'],
  [Route['registrations/city']]: Route['registration/city'],
  [Route['registrations/game']]: Route['registration/game'],
  [Route['registrations/game/theme']]: Route['registration/game/theme'],
  [Route['roles']]: Route['role'],
  [Route['themes']]: Route['theme'],
  [Route['themes/cover']]: Route['theme/cover'],
  [Route['timezones']]: Route['timezone'],
  [Route['user/cities']]: Route['user/cities'],
  [Route['users']]: Route['user'],
  [Route['users/cities']]: Route['user/cities'],
  [Route['users/role']]: Route['user/role'],
  [Route['venues']]: Route['venue'],
  [Route['venues/city']]: Route['venue/city'],
})

export const RoutePathname = Object.freeze({
  [Route['checkin']]: 'checkin',
  [Route['cities']]: 'cities',
  [Route['cities/country']]: 'cities/country',
  [Route['cities/currency']]: 'cities/currency',
  [Route['cities/timezone']]: 'cities/timezone',
  [Route['cities/venues']]: 'cities/venues',
  [Route['city']]: 'city/:city',
  [Route['city/country']]: 'city/:city/country',
  [Route['city/currency']]: 'city/:city/currency',
  [Route['city/timezone']]: 'city/:city/timezone',
  [Route['city/venue']]: 'city/:city/venue/:venue',
  [Route['city/venues']]: 'city/:city/venues',
  [Route['countries']]: 'countries',
  [Route['country']]: 'country/:country',
  [Route['currencies']]: 'currencies',
  [Route['currency']]: 'currency/:currency',
  [Route['game']]: 'game/:game',
  [Route['game/city']]: 'game/:game/city',
  [Route['game/registration']]: 'game/:game/registration/:registration',
  [Route['game/registrations']]: 'game/:game/registrations',
  [Route['game/registrations/export']]: 'game/:game/registrations/export',
  [Route['game/summary']]: 'game/:game/summary',
  [Route['game/theme']]: 'game/:game/theme',
  [Route['game/venue']]: 'game/:game/venue',
  [Route['games']]: 'games',
  [Route['games/city']]: 'games/city',
  [Route['games/registrations']]: 'games/registrations',
  [Route['games/registrations/export']]: 'games/registrations/export',
  [Route['games/summary']]: 'games/summary',
  [Route['games/theme']]: 'games/theme',
  [Route['games/venue']]: 'games/venue',
  [Route['registration']]: 'registration/:registration',
  [Route['registration/cancellation']]: 'registration/:registration/cancellation',
  [Route['registration/channel']]: 'registration/:registration/channel',
  [Route['registration/confirmation']]: 'registration/:registration/confirmation',
  [Route['registration/export']]: 'registration/:registration/export',
  [Route['registration/game']]: 'registration/:registration/game',
  [Route['registration/game/theme']]: 'registration/:registration/game/theme',
  [Route['registration/mailing']]: 'registration/:registration/mailing',
  [Route['registrations']]: 'registrations',
  [Route['registrations/city']]: 'registrations/city',
  [Route['registrations/game']]: 'registrations/game',
  [Route['registrations/game/theme']]: 'registrations/game/theme',
  [Route['registrations/export']]: 'registrations/export',
  [Route['role']]: 'role/:role',
  [Route['roles']]: 'roles',
  [Route['theme']]: 'theme/:theme',
  [Route['theme/cover']]: 'theme/:theme/cover',
  [Route['themes']]: 'themes',
  [Route['themes/cover']]: 'themes/cover',
  [Route['timezone']]: 'timezone/:timezone',
  [Route['timezones']]: 'timezones',
  [Route['user']]: 'user/:user',
  [Route['user/cities']]: 'user/:user/cities',
  [Route['user/city']]: 'user/:user/city/:city',
  [Route['user/password']]: 'user/:user/password',
  [Route['user/role']]: 'user/:user/role',
  [Route['users']]: 'users',
  [Route['users/cities']]: 'users/cities',
  [Route['users/password']]: 'users/password',
  [Route['users/role']]: 'users/role',
  [Route['venue']]: 'venue/:venue',
  [Route['venue/city']]: 'venue/:venue/city',
  [Route['venues']]: 'venues',
  [Route['venues/city']]: 'venues/city',
})

export const RouteParams = Object.freeze({
  [Route['checkin']]: [],
  [Route['checkins']]: [],
  [Route['cities']]: [],
  [Route['cities/country']]: [],
  [Route['cities/currency']]: [],
  [Route['cities/timezone']]: [],
  [Route['cities/venues']]: [],
  [Route['city']]: [':city'],
  [Route['city/country']]: [':city'],
  [Route['city/currency']]: [':city'],
  [Route['city/timezone']]: [':city'],
  [Route['city/venue']]: [':city', ':venue'],
  [Route['city/venues']]: [':city'],
  [Route['countries']]: [],
  [Route['country']]: [':country'],
  [Route['currencies']]: [],
  [Route['currency']]: [':currency'],
  [Route['game']]: [':game'],
  [Route['game/city']]: [':game'],
  [Route['game/registration']]: [':game', ':registration'],
  [Route['game/registrations']]: [':game'],
  [Route['game/registrations/export']]: [':game'],
  [Route['game/summary']]: [':game'],
  [Route['game/theme']]: [':game'],
  [Route['game/venue']]: [':game'],
  [Route['games']]: [],
  [Route['games/city']]: [],
  [Route['games/registrations']]: [],
  [Route['games/registrations/export']]: [],
  [Route['games/summary']]: [],
  [Route['games/theme']]: [],
  [Route['games/venue']]: [],
  [Route['registration']]: [':registration'],
  [Route['registration/cancellation']]: [':registration'],
  [Route['registration/channel']]: [':registration'],
  [Route['registration/confirmation']]: [':registration'],
  [Route['registration/export']]: [':registration'],
  [Route['registration/game']]: [':registration'],
  [Route['registration/game/theme']]: [':registration'],
  [Route['registration/mailing']]: [':registration'],
  [Route['registrations']]: [],
  [Route['registrations/city']]: [],
  [Route['registrations/game']]: [],
  [Route['registrations/game/theme']]: [],
  [Route['registrations/export']]: [],
  [Route['role']]: [':role'],
  [Route['roles']]: [],
  [Route['theme']]: [':theme'],
  [Route['theme/cover']]: [':theme'],
  [Route['themes']]: [],
  [Route['themes/cover']]: [],
  [Route['timezone']]: [':timezone'],
  [Route['timezones']]: [],
  [Route['user']]: [':user'],
  [Route['user/cities']]: [':user'],
  [Route['user/city']]: [':user', ':city'],
  [Route['user/password']]: [':user'],
  [Route['user/role']]: [':user'],
  [Route['users']]: [],
  [Route['users/cities']]: [],
  [Route['users/password']]: [],
  [Route['users/role']]: [],
  [Route['venue']]: [':venue'],
  [Route['venue/city']]: [':venue'],
  [Route['venues']]: [],
  [Route['venues/city']]: [],
})

export const RouteService = Object.freeze({
  [Route['checkin']]: Service['Checkin'],
  [Route['cities']]: Service['Cities'],
  [Route['cities/country']]: Service['Cities'],
  [Route['cities/currency']]: Service['Cities'],
  [Route['cities/timezone']]: Service['Cities'],
  [Route['cities/venues']]: Service['Cities'],
  [Route['city']]: Service['Cities'],
  [Route['city/country']]: Service['Cities'],
  [Route['city/currency']]: Service['Cities'],
  [Route['city/timezone']]: Service['Cities'],
  [Route['city/venues']]: Service['Cities'],
  [Route['countries']]: Service['Locations'],
  [Route['country']]: Service['Locations'],
  [Route['currencies']]: Service['Locations'],
  [Route['currency']]: Service['Locations'],
  [Route['game']]: Service['Games'],
  [Route['game/city']]: Service['Games'],
  [Route['game/registrations']]: Service['Games'],
  [Route['game/registrations/export']]: Service['Games'],
  [Route['game/summary']]: Service['Games'],
  [Route['game/theme']]: Service['Games'],
  [Route['game/venue']]: Service['Games'],
  [Route['games']]: Service['Games'],
  [Route['games/city']]: Service['Games'],
  [Route['games/registrations']]: Service['Games'],
  [Route['games/registrations/export']]: Service['Games'],
  [Route['games/summary']]: Service['Games'],
  [Route['games/theme']]: Service['Games'],
  [Route['games/venue']]: Service['Games'],
  [Route['registration']]: Service['Registrations'],
  [Route['registration/cancellation']]: Service['Registrations'],
  [Route['registration/channel']]: Service['Registrations'],
  [Route['registration/confirmation']]: Service['Registrations'],
  [Route['registration/game']]: Service['Registrations'],
  [Route['registration/mailing']]: Service['Registrations'],
  [Route['registrations']]: Service['Registrations'],
  [Route['registrations/city']]: Service['Registrations'],
  [Route['registrations/game']]: Service['Registrations'],
  [Route['registrations/game/theme']]: Service['Registrations'],
  [Route['registrations/export']]: Service['Registrations'],
  [Route['role']]: Service['Roles'],
  [Route['roles']]: Service['Roles'],
  [Route['theme']]: Service['Themes'],
  [Route['theme/cover']]: Service['Themes'],
  [Route['themes']]: Service['Themes'],
  [Route['themes/cover']]: Service['Themes'],
  [Route['timezone']]: Service['Locations'],
  [Route['timezones']]: Service['Locations'],
  [Route['user']]: Service['Users'],
  [Route['user/cities']]: Service['Users'],
  [Route['user/password']]: Service['Users'],
  [Route['user/role']]: Service['Users'],
  [Route['users']]: Service['Users'],
  [Route['users/cities']]: Service['Users'],
  [Route['users/role']]: Service['Users'],
  [Route['venue']]: Service['Venues'],
  [Route['venue/city']]: Service['Venues'],
  [Route['venues']]: Service['Venues'],
  [Route['venues/city']]: Service['Venues'],
})

export const ServiceRoutes = Object.freeze({
  [Service['Users']]: Object.freeze([
    Route['user'],
    Route['user/cities'],
    Route['user/password'],
    Route['user/role'],
    Route['users'],
    Route['users/cities'],
    Route['users/role'],
  ]),

  [Service['Roles']]: Object.freeze([
    Route['role'],
    Route['roles'],
  ]),

  [Service['Checkin']]: Object.freeze([
    Route['checkin'],
  ]),

  [Service['Locations']]: Object.freeze([
    Route['countries'],
    Route['country'],
    Route['currencies'],
    Route['currency'],
    Route['timezone'],
    Route['timezones'],
  ]),

  [Service['Cities']]: Object.freeze([
    Route['cities'],
    Route['cities/country'],
    Route['cities/currency'],
    Route['cities/timezone'],
    Route['cities/venues'],
    Route['city'],
    Route['city/country'],
    Route['city/currency'],
    Route['city/timezone'],
    Route['city/venues'],
  ]),

  [Service['Venues']]: Object.freeze([
    Route['venue'],
    Route['venue/city'],
    Route['venues'],
    Route['venues/city'],
  ]),

  [Service['Themes']]: Object.freeze([
    Route['theme'],
    Route['theme/cover'],
    Route['themes'],
    Route['themes/cover'],
  ]),

  [Service['Games']]: Object.freeze([
    Route['game'],
    Route['game/city'],
    Route['game/registrations'],
    Route['game/registrations/export'],
    Route['game/summary'],
    Route['game/theme'],
    Route['game/venue'],
    Route['games'],
    Route['games/city'],
    Route['games/registrations'],
    Route['games/registrations/export'],
    Route['games/summary'],
    Route['games/theme'],
    Route['games/venue'],
  ]),

  [Service['Registrations']]: Object.freeze([
    Route['registration'],
    Route['registration/cancellation'],
    Route['registration/channel'],
    Route['registration/confirmation'],
    Route['registration/game'],
    Route['registration/mailing'],
    Route['registrations'],
    Route['registrations/city'],
    Route['registrations/game'],
    Route['registrations/game/theme'],
    Route['registrations/export'],
  ]),

  [Service['Procedures']]: Object.freeze([]),

  [Service['Integrations']]: Object.freeze([]),

  [Service['Updates']]: Object.freeze([]),

  [Service['Hub']]: Object.freeze([]),

  [Service['Landing']]: Object.freeze([]),

  [Service['Vkma']]: Object.freeze([]),
})

export const inferRoute = Object.freeze(
  /** @returns {typeof Route[keyof typeof Route] | 'Unknown'} */
  x => Route[x] ?? 'Unknown',
)

export const inferRouteCardinality = Object.freeze(
  /** @returns {typeof RouteCardinality[keyof typeof RouteCardinality] | 'Unknown'} */
  x => RouteCardinality[x] ?? 'Unknown',
)

export const inferRouteRelation = Object.freeze(
  /** @returns {typeof RouteRelation[keyof typeof RouteRelation] | 'Unknown'} */
  x => RouteRelation[x] ?? 'Unknown',
)

export const inferRoutePathname = Object.freeze(
  /** @returns {typeof RoutePathname[keyof typeof RoutePathname] | 'Unknown'} */
  x => RoutePathname[x] ?? 'Unknown',
)

export const inferRouteParams = Object.freeze(
  /** @returns {typeof RouteParams[keyof typeof RouteParams] | 'Unknown'} */
  x => RouteParams[x] ?? 'Unknown',
)

export const inferRouteService = Object.freeze(
  /** @returns {typeof RouteService[keyof typeof RouteService] | 'Unknown'} */
  x => RouteService[x] ?? 'Unknown',
)

export const inferServiceRoutes = Object.freeze(
  /** @returns {typeof ServiceRoutes[keyof typeof ServiceRoutes] | 'Unknown'} */
  x => ServiceRoutes[x] ?? 'Unknown',
)
