import { Kind } from './kind.js'
import { Numerosity } from './numerosity.js'
import { Service } from './service.js'

export const Route = Object.freeze({
  'checkin': 'checkin',
  'checkins': 'checkins',
  'cities': 'cities',
  'cities/country': 'cities/country',
  'cities/currency': 'cities/currency',
  'cities/timezone': 'cities/timezone',
  'cities/venues': 'cities/venues',
  'city': 'city',
  'city/country': 'city/country',
  'city/currency': 'city/currency',
  'city/timezone': 'city/timezone',
  'city/venues': 'city/venues',
  'countries': 'countries',
  'country': 'country',
  'currencies': 'currencies',
  'currency': 'currency',
  'game': 'game',
  'game/city': 'game/city',
  'game/registrations': 'game/registrations',
  'game/registrations/export': 'game/registrations/export',
  'game/summary': 'game/summary',
  'game/theme': 'game/theme',
  'game/venue': 'game/venue',
  'games': 'games',
  'games/city': 'games/city',
  'games/registrations': 'games/registrations',
  'games/registrations/export': 'games/registrations/export',
  'games/summary': 'games/summary',
  'games/theme': 'games/theme',
  'games/venue': 'games/venue',
  'registration': 'registration',
  'registration/cancellation': 'registration/cancellation',
  'registration/channel': 'registration/channel',
  'registration/confirmation': 'registration/confirmation',
  'registration/export': 'registration/export',
  'registration/game': 'registration/game',
  'registration/mailing': 'registration/mailing',
  'registrations': 'registrations',
  'registrations/export': 'registrations/export',
  'role': 'role',
  'roles': 'roles',
  'theme': 'theme',
  'theme/cover': 'theme/cover',
  'themes': 'themes',
  'themes/cover': 'themes/cover',
  'timezone': 'timezone',
  'timezones': 'timezones',
  'user': 'user',
  'user/cities': 'user/cities',
  'user/password': 'user/password',
  'user/role': 'user/role',
  'users': 'users',
  'users/cities': 'users/cities',
  'users/password': 'users/password',
  'users/role': 'users/role',
  'venue': 'venue',
  'venue/city': 'venue/city',
  'venues': 'venues',
  'venues/city': 'venues/city',
})

export const RouteNumerosity = Object.freeze({
  [Route['checkin']]: Numerosity['Singular'],
  [Route['checkins']]: Numerosity['Plural'],
  [Route['cities']]: Numerosity['Plural'],
  [Route['cities/country']]: Numerosity['Plural'],
  [Route['cities/currency']]: Numerosity['Plural'],
  [Route['cities/timezone']]: Numerosity['Plural'],
  [Route['cities/venues']]: Numerosity['Plural'],
  [Route['city']]: Numerosity['Singular'],
  [Route['city/country']]: Numerosity['Singular'],
  [Route['city/currency']]: Numerosity['Singular'],
  [Route['city/timezone']]: Numerosity['Singular'],
  [Route['city/venues']]: Numerosity['Singular'],
  [Route['countries']]: Numerosity['Plural'],
  [Route['country']]: Numerosity['Singular'],
  [Route['currencies']]: Numerosity['Plural'],
  [Route['currency']]: Numerosity['Singular'],
  [Route['game']]: Numerosity['Singular'],
  [Route['game/city']]: Numerosity['Singular'],
  [Route['game/registrations']]: Numerosity['Plural'],
  [Route['game/registrations/export']]: Numerosity['Singular'],
  [Route['game/summary']]: Numerosity['Singular'],
  [Route['game/theme']]: Numerosity['Singular'],
  [Route['game/venue']]: Numerosity['Singular'],
  [Route['games']]: Numerosity['Plural'],
  [Route['games/city']]: Numerosity['Plural'],
  [Route['games/registrations']]: Numerosity['Plural'],
  [Route['games/registrations/export']]: Numerosity['Plural'],
  [Route['games/summary']]: Numerosity['Plural'],
  [Route['games/theme']]: Numerosity['Plural'],
  [Route['games/venue']]: Numerosity['Plural'],
  [Route['registration']]: Numerosity['Singular'],
  [Route['registration/cancellation']]: Numerosity['Singular'],
  [Route['registration/channel']]: Numerosity['Singular'],
  [Route['registration/confirmation']]: Numerosity['Singular'],
  [Route['registration/export']]: Numerosity['Singular'],
  [Route['registration/game']]: Numerosity['Singular'],
  [Route['registration/mailing']]: Numerosity['Singular'],
  [Route['registrations']]: Numerosity['Plural'],
  [Route['registrations/export']]: Numerosity['Singular'],
  [Route['role']]: Numerosity['Singular'],
  [Route['roles']]: Numerosity['Plural'],
  [Route['theme']]: Numerosity['Singular'],
  [Route['theme/cover']]: Numerosity['Singular'],
  [Route['themes']]: Numerosity['Plural'],
  [Route['themes/cover']]: Numerosity['Plural'],
  [Route['timezone']]: Numerosity['Singular'],
  [Route['timezones']]: Numerosity['Plural'],
  [Route['user']]: Numerosity['Singular'],
  [Route['user/cities']]: Numerosity['Plural'],
  [Route['user/password']]: Numerosity['Singular'],
  [Route['user/role']]: Numerosity['Singular'],
  [Route['users']]: Numerosity['Plural'],
  [Route['users/cities']]: Numerosity['Plural'],
  [Route['users/password']]: Numerosity['Plural'],
  [Route['users/role']]: Numerosity['Plural'],
  [Route['venue']]: Numerosity['Singular'],
  [Route['venue/city']]: Numerosity['Singular'],
  [Route['venues']]: Numerosity['Plural'],
  [Route['venues/city']]: Numerosity['Plural'],
})

export const RouteRelation = Object.freeze({
  [Route['checkin']]: Route['checkin'],
  [Route['checkins']]: Route['checkin'],
  [Route['cities']]: Route['city'],
  [Route['cities/country']]: Route['city/country'],
  [Route['cities/currency']]: Route['city/currency'],
  [Route['cities/timezone']]: Route['city/timezone'],
  [Route['cities/venues']]: Route['city/venues'],
  [Route['city']]: Route['city'],
  [Route['city/country']]: Route['city/country'],
  [Route['city/currency']]: Route['city/currency'],
  [Route['city/timezone']]: Route['city/timezone'],
  [Route['city/venues']]: Route['city/venues'],
  [Route['countries']]: Route['country'],
  [Route['country']]: Route['country'],
  [Route['currencies']]: Route['currency'],
  [Route['currency']]: Route['currency'],
  [Route['game']]: Route['game'],
  [Route['game/city']]: Route['game/city'],
  [Route['game/registrations']]: Route['game/registrations'],
  [Route['game/registrations/export']]: Route['game/registrations/export'],
  [Route['game/summary']]: Route['game/summary'],
  [Route['game/theme']]: Route['game/theme'],
  [Route['game/venue']]: Route['game/venue'],
  [Route['games']]: Route['game'],
  [Route['games/city']]: Route['game/city'],
  [Route['games/registrations']]: Route['game/registrations'],
  [Route['games/registrations/export']]: Route['game/registrations/export'],
  [Route['games/summary']]: Route['game/summary'],
  [Route['games/theme']]: Route['game/theme'],
  [Route['games/venue']]: Route['game/venue'],
  [Route['registration']]: Route['registration'],
  [Route['registration/export']]: Route['registration/export'],
  [Route['registrations']]: Route['registration'],
  [Route['registrations/export']]: Route['registration/export'],
  [Route['role']]: Route['role'],
  [Route['roles']]: Route['role'],
  [Route['theme']]: Route['theme'],
  [Route['theme/cover']]: Route['theme/cover'],
  [Route['themes']]: Route['theme'],
  [Route['themes/cover']]: Route['theme/cover'],
  [Route['timezone']]: Route['timezone'],
  [Route['timezones']]: Route['timezone'],
  [Route['user']]: Route['user'],
  [Route['user/cities']]: Route['user/cities'],
  [Route['user/password']]: Route['user/password'],
  [Route['user/role']]: Route['user/role'],
  [Route['users']]: Route['user'],
  [Route['users/cities']]: Route['user/cities'],
  [Route['users/role']]: Route['user/role'],
  [Route['venue']]: Route['venue'],
  [Route['venue/city']]: Route['venue/city'],
  [Route['venues']]: Route['venue'],
  [Route['venues/city']]: Route['venue/city'],
})

export const RoutePathname = Object.freeze({
  [Route['checkin']]: 'checkin',
  [Route['checkins']]: 'checkins',
  [Route['cities']]: 'cities',
  [Route['cities/country']]: 'cities/country',
  [Route['cities/currency']]: 'cities/currency',
  [Route['cities/timezone']]: 'cities/timezone',
  [Route['cities/venues']]: 'cities/venues',
  [Route['city']]: 'city/:city',
  [Route['city/country']]: 'city/:city/country',
  [Route['city/currency']]: 'city/:city/currency',
  [Route['city/timezone']]: 'city/:city/timezone',
  [Route['city/venues']]: 'city/:city/venues',
  [Route['countries']]: 'countries',
  [Route['country']]: 'country/:country',
  [Route['currencies']]: 'currencies',
  [Route['currency']]: 'currency/:currency',
  [Route['game']]: 'game/:game',
  [Route['game/city']]: 'game/:game/city',
  [Route['game/registrations']]: 'game/:game/registrations',
  [Route['game/registrations/export']]: 'game/:game/registrations/export',
  [Route['game/summary']]: 'game/:game/summary',
  [Route['game/theme']]: 'game/:game/theme',
  [Route['game/venue']]: 'game/:game/venue',
  [Route['games']]: 'games',
  [Route['games/city']]: 'games/city',
  [Route['games/registrations']]: 'games/registrations',
  [Route['games/registrations/export']]: 'games/registrations/export',
  [Route['games/summary']]: 'games/summary',
  [Route['games/theme']]: 'games/theme',
  [Route['games/venue']]: 'games/venue',
  [Route['registration']]: 'registration/:registration',
  [Route['registration/cancellation']]: 'registration/:registration/cancellation',
  [Route['registration/channel']]: 'registration/:registration/channel',
  [Route['registration/confirmation']]: 'registration/:registration/confirmation',
  [Route['registration/export']]: 'registration/:registration/export',
  [Route['registration/game']]: 'registration/:registration/game',
  [Route['registration/mailing']]: 'registration/:registration/mailing',
  [Route['registrations']]: 'registrations',
  [Route['registrations/export']]: 'registrations/export',
  [Route['role']]: 'role/:role',
  [Route['roles']]: 'roles',
  [Route['theme']]: 'theme/:theme',
  [Route['theme/cover']]: 'theme/:theme/cover',
  [Route['themes']]: 'themes',
  [Route['themes/cover']]: 'themes/cover',
  [Route['timezone']]: 'timezone/:timezone',
  [Route['timezones']]: 'timezones',
  [Route['user']]: 'user/:user',
  [Route['user/cities']]: 'user/:user/cities',
  [Route['user/password']]: 'user/:user/password',
  [Route['user/role']]: 'user/:user/role',
  [Route['users']]: 'users',
  [Route['users/cities']]: 'users/cities',
  [Route['users/role']]: 'users/role',
  [Route['venue']]: 'venue/:venue',
  [Route['venue/city']]: 'venue/:venue/city',
  [Route['venues']]: 'venues',
  [Route['venues/city']]: 'venues/city',
})

export const RouteKind = Object.freeze({
  [Route['checkin']]: Kind['Atomic'],
  [Route['checkins']]: Kind['Atomic'],
  [Route['cities']]: Kind['Atomic'],
  [Route['cities/country']]: Kind['Composite'],
  [Route['cities/currency']]: Kind['Composite'],
  [Route['cities/timezone']]: Kind['Composite'],
  [Route['cities/venues']]: Kind['Composite'],
  [Route['city']]: Kind['Atomic'],
  [Route['city/country']]: Kind['Composite'],
  [Route['city/currency']]: Kind['Composite'],
  [Route['city/timezone']]: Kind['Composite'],
  [Route['city/venues']]: Kind['Composite'],
  [Route['countries']]: Kind['Atomic'],
  [Route['country']]: Kind['Atomic'],
  [Route['currencies']]: Kind['Atomic'],
  [Route['currency']]: Kind['Atomic'],
  [Route['game']]: Kind['Atomic'],
  [Route['game/city']]: Kind['Composite'],
  [Route['game/registrations']]: Kind['Composite'],
  [Route['game/registrations/export']]: Kind['Procedure'],
  [Route['game/summary']]: Kind['Composite'],
  [Route['game/theme']]: Kind['Composite'],
  [Route['game/venue']]: Kind['Composite'],
  [Route['games']]: Kind['Atomic'],
  [Route['games/city']]: Kind['Composite'],
  [Route['games/registrations']]: Kind['Composite'],
  [Route['games/registrations/export']]: Kind['Procedure'],
  [Route['games/summary']]: Kind['Composite'],
  [Route['games/theme']]: Kind['Composite'],
  [Route['games/venue']]: Kind['Composite'],
  [Route['registration']]: Kind['Atomic'],
  [Route['registration/cancellation']]: Kind['Composite'],
  [Route['registration/channel']]: Kind['Composite'],
  [Route['registration/confirmation']]: Kind['Composite'],
  [Route['registration/export']]: Kind['Procedure'],
  [Route['registration/game']]: Kind['Composite'],
  [Route['registration/mailing']]: Kind['Composite'],
  [Route['registrations']]: Kind['Atomic'],
  [Route['registrations/export']]: Kind['Procedure'],
  [Route['role']]: Kind['Atomic'],
  [Route['roles']]: Kind['Atomic'],
  [Route['theme']]: Kind['Atomic'],
  [Route['theme/cover']]: Kind['Composite'],
  [Route['themes']]: Kind['Atomic'],
  [Route['themes/cover']]: Kind['Composite'],
  [Route['timezone']]: Kind['Atomic'],
  [Route['timezones']]: Kind['Atomic'],
  [Route['user']]: Kind['Atomic'],
  [Route['user/cities']]: Kind['Composite'],
  [Route['user/password']]: Kind['Composite'],
  [Route['user/role']]: Kind['Composite'],
  [Route['users']]: Kind['Atomic'],
  [Route['users/cities']]: Kind['Composite'],
  [Route['users/password']]: Kind['Composite'],
  [Route['users/role']]: Kind['Composite'],
  [Route['venue']]: Kind['Atomic'],
  [Route['venue/city']]: Kind['Composite'],
  [Route['venues']]: Kind['Atomic'],
  [Route['venues/city']]: Kind['Composite'],
})

export const CompositeRouteField = Object.freeze({
  [Route['cities/country']]: 'country',
  [Route['cities/currency']]: 'currency',
  [Route['cities/timezone']]: 'timezone',
  [Route['cities/venues']]: 'venues',
  [Route['city/country']]: 'country',
  [Route['city/currency']]: 'currency',
  [Route['city/timezone']]: 'timezone',
  [Route['city/venues']]: 'venues',
  [Route['game/city']]: 'city',
  [Route['game/registrations']]: 'registrations',
  [Route['game/summary']]: 'summary',
  [Route['game/theme']]: 'theme',
  [Route['game/venue']]: 'venue',
  [Route['games/city']]: 'city',
  [Route['games/registrations']]: 'registrations',
  [Route['games/summary']]: 'summary',
  [Route['games/theme']]: 'theme',
  [Route['games/venue']]: 'venue',
  [Route['registration/cancellation']]: 'cancellation',
  [Route['registration/channel']]: 'channel',
  [Route['registration/confirmation']]: 'confirmation',
  [Route['registration/game']]: 'game',
  [Route['registration/mailing']]: 'mailing',
  [Route['theme/cover']]: 'cover',
  [Route['themes/cover']]: 'cover',
  [Route['user/cities']]: 'cities',
  [Route['user/password']]: 'password',
  [Route['user/role']]: 'role',
  [Route['users/cities']]: 'cities',
  [Route['users/password']]: 'password',
  [Route['users/role']]: 'role',
  [Route['venue/city']]: 'city',
  [Route['venues/city']]: 'city',
})

export const RouteParams = Object.freeze({
  [Route['checkin']]: [],
  [Route['checkins']]: [],
  [Route['cities']]: [],
  [Route['cities/country']]: [],
  [Route['cities/currency']]: [],
  [Route['cities/timezone']]: [],
  [Route['cities/venues']]: [],
  [Route['city']]: [':city'],
  [Route['city/country']]: [':city'],
  [Route['city/currency']]: [':city'],
  [Route['city/timezone']]: [':city'],
  [Route['city/venues']]: [':city'],
  [Route['countries']]: [],
  [Route['country']]: [':country'],
  [Route['currencies']]: [],
  [Route['currency']]: [':currency'],
  [Route['game']]: [':game'],
  [Route['game/city']]: [':game'],
  [Route['game/registrations']]: [':game'],
  [Route['game/registrations/export']]: [':game'],
  [Route['game/summary']]: [':game'],
  [Route['game/theme']]: [':game'],
  [Route['game/venue']]: [':game'],
  [Route['games']]: [],
  [Route['games/city']]: [],
  [Route['games/registrations']]: [],
  [Route['games/registrations/export']]: [],
  [Route['games/summary']]: [],
  [Route['games/theme']]: [],
  [Route['games/venue']]: [],
  [Route['registration']]: [':registration'],
  [Route['registration/cancellation']]: [':registration'],
  [Route['registration/channel']]: [':registration'],
  [Route['registration/confirmation']]: [':registration'],
  [Route['registration/export']]: [':registration'],
  [Route['registration/game']]: [':registration'],
  [Route['registration/mailing']]: [':registration'],
  [Route['registrations']]: [],
  [Route['registrations/export']]: [],
  [Route['role']]: [':role'],
  [Route['roles']]: [],
  [Route['theme']]: [':theme'],
  [Route['theme/cover']]: [':theme'],
  [Route['themes']]: [],
  [Route['themes/cover']]: [],
  [Route['timezone']]: [':timezone'],
  [Route['timezones']]: [],
  [Route['user']]: [':user'],
  [Route['user/cities']]: [':user'],
  [Route['user/password']]: [':user'],
  [Route['user/role']]: [':user'],
  [Route['users']]: [],
  [Route['users/cities']]: [],
  [Route['users/role']]: [],
  [Route['venue']]: [':venue'],
  [Route['venue/city']]: [':venue'],
  [Route['venues']]: [],
  [Route['venues/city']]: [],
})

export const RouteService = Object.freeze({
  [Route['checkin']]: Service['Checkin'],
  [Route['cities']]: Service['Cities'],
  [Route['cities/country']]: Service['Cities'],
  [Route['cities/currency']]: Service['Cities'],
  [Route['cities/timezone']]: Service['Cities'],
  [Route['cities/venues']]: Service['Cities'],
  [Route['city']]: Service['Cities'],
  [Route['city/country']]: Service['Cities'],
  [Route['city/currency']]: Service['Cities'],
  [Route['city/timezone']]: Service['Cities'],
  [Route['city/venues']]: Service['Cities'],
  [Route['countries']]: Service['Locations'],
  [Route['country']]: Service['Locations'],
  [Route['currencies']]: Service['Locations'],
  [Route['currency']]: Service['Locations'],
  [Route['game']]: Service['Games'],
  [Route['game/city']]: Service['Games'],
  [Route['game/registrations']]: Service['Games'],
  [Route['game/registrations/export']]: Service['Games'],
  [Route['game/summary']]: Service['Games'],
  [Route['game/theme']]: Service['Games'],
  [Route['game/venue']]: Service['Games'],
  [Route['games']]: Service['Games'],
  [Route['games/city']]: Service['Games'],
  [Route['games/registrations']]: Service['Games'],
  [Route['games/registrations/export']]: Service['Games'],
  [Route['games/summary']]: Service['Games'],
  [Route['games/theme']]: Service['Games'],
  [Route['games/venue']]: Service['Games'],
  [Route['registration']]: Service['Registrations'],
  [Route['registration/cancellation']]: Service['Registrations'],
  [Route['registration/channel']]: Service['Registrations'],
  [Route['registration/confirmation']]: Service['Registrations'],
  [Route['registration/game']]: Service['Registrations'],
  [Route['registration/mailing']]: Service['Registrations'],
  [Route['registrations']]: Service['Registrations'],
  [Route['registrations/export']]: Service['Registrations'],
  [Route['role']]: Service['Roles'],
  [Route['roles']]: Service['Roles'],
  [Route['theme']]: Service['Themes'],
  [Route['theme/cover']]: Service['Themes'],
  [Route['themes']]: Service['Themes'],
  [Route['themes/cover']]: Service['Themes'],
  [Route['timezone']]: Service['Locations'],
  [Route['timezones']]: Service['Locations'],
  [Route['user']]: Service['Users'],
  [Route['user/cities']]: Service['Users'],
  [Route['user/password']]: Service['Users'],
  [Route['user/role']]: Service['Users'],
  [Route['users']]: Service['Users'],
  [Route['users/cities']]: Service['Users'],
  [Route['users/role']]: Service['Users'],
  [Route['venue']]: Service['Venues'],
  [Route['venue/city']]: Service['Venues'],
  [Route['venues']]: Service['Venues'],
  [Route['venues/city']]: Service['Venues'],
})

export const ServiceRoutes = Object.freeze({
  [Service['Users']]: Object.freeze([
    Route['user'],
    Route['user/cities'],
    Route['user/password'],
    Route['user/role'],
    Route['users'],
    Route['users/cities'],
    Route['users/role'],
  ]),

  [Service['Roles']]: Object.freeze([
    Route['role'],
    Route['roles'],
  ]),

  [Service['Checkin']]: Object.freeze([
    Route['checkin'],
  ]),

  [Service['Locations']]: Object.freeze([
    Route['countries'],
    Route['country'],
    Route['currencies'],
    Route['currency'],
    Route['timezone'],
    Route['timezones'],
  ]),

  [Service['Cities']]: Object.freeze([
    Route['cities'],
    Route['cities/country'],
    Route['cities/currency'],
    Route['cities/timezone'],
    Route['cities/venues'],
    Route['city'],
    Route['city/country'],
    Route['city/currency'],
    Route['city/timezone'],
    Route['city/venues'],
  ]),

  [Service['Venues']]: Object.freeze([
    Route['venue'],
    Route['venue/city'],
    Route['venues'],
    Route['venues/city'],
  ]),

  [Service['Themes']]: Object.freeze([
    Route['theme'],
    Route['theme/cover'],
    Route['themes'],
    Route['themes/cover'],
  ]),

  [Service['Games']]: Object.freeze([
    Route['game'],
    Route['game/city'],
    Route['game/registrations'],
    Route['game/registrations/export'],
    Route['game/summary'],
    Route['game/theme'],
    Route['game/venue'],
    Route['games'],
    Route['games/city'],
    Route['games/registrations'],
    Route['games/registrations/export'],
    Route['games/summary'],
    Route['games/theme'],
    Route['games/venue'],
  ]),

  [Service['Registrations']]: Object.freeze([
    Route['registration'],
    Route['registration/cancellation'],
    Route['registration/channel'],
    Route['registration/confirmation'],
    Route['registration/game'],
    Route['registration/mailing'],
    Route['registrations'],
    Route['registrations/export'],
  ]),

  [Service['Procedures']]: Object.freeze([]),

  [Service['Integrations']]: Object.freeze([]),

  [Service['Updates']]: Object.freeze([]),

  [Service['Hub']]: Object.freeze([]),

  [Service['Landing']]: Object.freeze([]),

  [Service['Vkma']]: Object.freeze([]),
})

/** @returns {typeof Route[keyof typeof Route] | 'Unknown'} */
export const inferRoute = x => Route[x] ?? 'Unknown'

/** @returns {typeof RouteNumerosity[keyof typeof RouteNumerosity] | 'Unknown'} */
export const inferRouteNumerosity = x => RouteNumerosity[x] ?? 'Unknown'

/** @returns {typeof RouteRelation[keyof typeof RouteRelation] | 'Unknown'} */
export const inferRouteRelation = x => RouteRelation[x] ?? 'Unknown'

/** @returns {typeof RoutePathname[keyof typeof RoutePathname] | 'Unknown'} */
export const inferRoutePathname = x => RoutePathname[x] ?? 'Unknown'

/** @returns {typeof RouteKind[keyof typeof RouteKind] | 'Unknown'} */
export const inferRouteKind = x => RouteKind[x] ?? 'Unknown'

/** @returns {typeof CompositeRouteField[keyof typeof CompositeRouteField] | 'Unknown'} */
export const inferCompositeRouteField = x => CompositeRouteField[x] ?? 'Unknown'

/** @returns {typeof RouteParams[keyof typeof RouteParams] | 'Unknown'} */
export const inferRouteParams = x => RouteParams[x] ?? 'Unknown'

/** @returns {typeof RouteService[keyof typeof RouteService] | 'Unknown'} */
export const inferRouteService = x => RouteService[x] ?? 'Unknown'

/** @returns {typeof ServiceRoutes[keyof typeof ServiceRoutes] | 'Unknown'} */
export const inferServiceRoutes = x => ServiceRoutes[x] ?? 'Unknown'
