export var Service = /** @type {const} */ ({
  'Users': 'Users',
  'Roles': 'Roles',
  'Checkin': 'Checkin',
  'Locations': 'Locations',
  'Cities': 'Cities',
  'Venues': 'Venues',
  'Themes': 'Themes',
  'Games': 'Games',
  'Registrations': 'Registrations',
  'Files': 'Files',
  'Procedures': 'Procedures',
  'Integrations': 'Integrations',
  'Updates': 'Updates',
  'Hub': 'Hub',
  'Landing': 'Landing',
  'Vkma': 'Vkma',
  'Minio': 'Minio',
})

export var Services = [
  Service['Users'],
  Service['Roles'],
  Service['Checkin'],
  Service['Locations'],
  Service['Cities'],
  Service['Venues'],
  Service['Themes'],
  Service['Games'],
  Service['Registrations'],
  Service['Files'],
  Service['Procedures'],
  Service['Integrations'],
  Service['Updates'],
  Service['Hub'],
  Service['Landing'],
  Service['Vkma'],
  Service['Minio'],
]
