import { Mode } from './mode.js'
import { Runtime } from './runtime.js'

export const Service = Object.freeze({
  'Users': 'Users',
  'Roles': 'Roles',
  'Checkin': 'Checkin',
  'Locations': 'Locations',
  'Cities': 'Cities',
  'Venues': 'Venues',
  'Themes': 'Themes',
  'Games': 'Games',
  'Registrations': 'Registrations',
  'Files': 'Files',
  'Procedures': 'Procedures',
  'Integrations': 'Integrations',
  'Updates': 'Updates',
  'Hub': 'Hub',
  'Landing': 'Landing',
  'Vkma': 'Vkma',
  'Minio': 'Minio',
})

export const Services = Object.freeze([
  Service['Users'],
  Service['Roles'],
  Service['Checkin'],
  Service['Locations'],
  Service['Cities'],
  Service['Venues'],
  Service['Themes'],
  Service['Games'],
  Service['Registrations'],
  Service['Files'],
  Service['Procedures'],
  Service['Integrations'],
  Service['Updates'],
  Service['Hub'],
  Service['Landing'],
  Service['Vkma'],
  Service['Minio'],
])

export const ServiceRuntime = Object.freeze({
  [Service['Users']]: Runtime['Deno'],
  [Service['Roles']]: Runtime['Deno'],
  [Service['Checkin']]: Runtime['Deno'],
  [Service['Locations']]: Runtime['Deno'],
  [Service['Cities']]: Runtime['Deno'],
  [Service['Venues']]: Runtime['Deno'],
  [Service['Themes']]: Runtime['Deno'],
  [Service['Games']]: Runtime['Deno'],
  [Service['Registrations']]: Runtime['Deno'],
  [Service['Files']]: Runtime['Bun'],
  [Service['Procedures']]: Runtime['Bun'],
  [Service['Integrations']]: Runtime['Bun'],
  [Service['Updates']]: Runtime['Bun'],
  [Service['Hub']]: Runtime['Node'],
  [Service['Landing']]: Runtime['Node'],
  [Service['Vkma']]: Runtime['Vite'],
  [Service['Minio']]: Mode['Unknown'],
})
