name: Codegen @shakerquiz/utilities

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - uses: oven-sh/setup-bun@v2
      - run: npm ci
      - run: npm run prepublishOnly
